'''
Created on Aug 20, 2012

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle         Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal         Pn=n(3n1)/2         1, 5, 12, 22, 35, ...
Hexagonal         Hn=n(2n1)         1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

@author: frouglas
'''

import math 

def genhex(x):
    hexNum = x*(2*x-1)
    return hexNum

def gentri(x):
    triNum = x*(x+1)/2
    return triNum

def genpent(x):
    pentNum = x*(3*x-1)/2
    return pentNum

def isPent(x):
    root = (1+math.sqrt(1+24*x))/6
    if root == int(root):
        return root
    else: 
        return 0
    
def isTri(x):
    root = (-1+math.sqrt(1+8*x))/2
    if root == int(root):
        return root
    else: 
        return 0

found = 0
i = 1
iHex = 0

while(found==0):
    iHex = genhex(i)
    if (isPent(iHex)!=0) & (isTri(iHex)!=0):
        print(str(iHex) + " is a triangle num (" + str(int(isTri(iHex))) + "), a pentagonal number (" + str(int(isPent(iHex))) + "), and a hexagonal number (" + str(i) + ")")
        if iHex > 40755:
            found = 1
            break
    i += 1